<?php
session_start();
require_once('connectdb.php');
$customerid = $_SESSION['customer_id'];
$accountName = $_POST['accountName'];
$address = $_POST['address'];
$email = $_POST['email'];
$addInfoToDB = $db->prepare('UPDATE customerdetails SET name = ?, default_address = ? WHERE customer_id = ?');
$addInfoToDB->bindParam(1, $accountName);
$addInfoToDB->bindParam(2, $address);
$addInfoToDB->bindParam(3, $customerid);
$addInfoToDB->execute();
$getUserID = $db->prepare('SELECT user_id FROM customerdetails WHERE customer_id = ?');
$getUserID->bindParam(1, $customerid);
$getUserID->execute();
$userid = $getUserID->fetch();
$addInfoToDB = $db->prepare('UPDATE logindetails SET email = ? WHERE user_id = ?');
$addInfoToDB->bindParam(1, $email);
$addInfoToDB->bindParam(2, $userid['user_id']);
$addInfoToDB->execute();